"""Drift guard for the frontend fixture.

The frontend currently renders from `frontend/src/fixtures/race.json`,
generated by `scripts/export_fixture.py`, because Phase 5's API isn't built.
A hand-exported fixture goes stale silently the moment anything upstream is
refit — and this session's parameters moved three times. The concrete cost:
a 25% win fraction measured at `MIN_FOLLOWING_GAP_S = 0.3` was quoted in
prose after the floor had already been refitted to 0.580, i.e. the number
was wrong when it was written down.

So the fixture carries a parameter fingerprint, and this test asserts it
matches the live constants. If a refit invalidates the fixture, a test fails
instead of the UI quietly showing a number nobody re-derived. Same pattern as
`scripts/fit_noise_autocorrelation.py` and `scripts/fit_min_following_gap.py`
failing loudly on drift.

Fix on failure: re-run `python backend/scripts/export_fixture.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from pitwall.simulation.lap_time import AR1_PHI
from pitwall.simulation.position import MIN_FOLLOWING_GAP_S

FIXTURE_PATH = Path(__file__).resolve().parents[2] / "frontend" / "src" / "fixtures" / "race.json"


@pytest.fixture(scope="module")
def fixture() -> dict:
    if not FIXTURE_PATH.exists():
        pytest.skip(f"{FIXTURE_PATH} not generated; run scripts/export_fixture.py")
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def test_fixture_simulation_constants_match_live_code(fixture):
    fingerprint = fixture["meta"]["paramFingerprint"]
    assert fingerprint["minFollowingGapS"] == pytest.approx(MIN_FOLLOWING_GAP_S), (
        "fixture was generated with a different MIN_FOLLOWING_GAP_S -- the margin the UI "
        "reports is stale. Re-run scripts/export_fixture.py."
    )
    assert fingerprint["ar1Phi"] == pytest.approx(AR1_PHI), (
        "fixture was generated with a different AR1_PHI -- the ensemble spread (and so the "
        "win fraction) is stale. Re-run scripts/export_fixture.py."
    )


def test_fixture_fitted_parameters_match_a_fresh_fit(fixture):
    """The fingerprint also covers *fitted* values, which move when the
    fitting code changes even if no constant does."""
    from pitwall.ingestion.catalogue import get_entry
    from pitwall.ingestion.loader import load_race
    from pitwall.parameters.fit_all import fit_catalogue_with_pooled_dirty_air

    entry = get_entry(fixture["meta"]["raceKey"])
    snapshot, _ = load_race(entry.year, entry.fastf1_event_identifier)
    params = fit_catalogue_with_pooled_dirty_air([snapshot])[snapshot.race_key]

    fingerprint = fixture["meta"]["paramFingerprint"]
    assert fingerprint["pitLaneLossS"] == pytest.approx(params.pit_lane_loss_s, abs=1e-3)
    assert fingerprint["overtakeDifficulty"] == pytest.approx(params.overtake_difficulty, abs=1e-5)
    assert fingerprint["dirtyAirMaxPenaltyS"] == pytest.approx(params.dirty_air.max_penalty_s, abs=1e-5)
    assert fingerprint["dirtyAirDecayScaleS"] == pytest.approx(params.dirty_air.decay_scale_s, abs=1e-5)


def test_fixture_carries_seed_traces_not_only_a_median(fixture):
    """Spec 6.10: a counterfactual is a distribution. The chart must be able
    to draw real seed traces rather than presenting a median line as if it
    were a single universe any seed produced."""
    cf = fixture["counterfactual"]
    assert cf["seedSeries"], "no per-seed traces exported; the chart can only draw a median"
    assert len(cf["seedSeries"]) >= 5
    for trace in cf["seedSeries"]:
        assert trace["points"], f"seed {trace['seed']} has no post-fork points"
        assert min(p["lap"] for p in trace["points"]) >= cf["divergenceLap"]


def test_fixture_win_fraction_is_consistent_with_its_own_distribution(fixture):
    """Guards the specific error that motivated this file: a win fraction
    quoted from a different parameter set than the distribution beside it."""
    cf = fixture["counterfactual"]
    distribution = cf["outcome"]["positionDistribution"]
    n_wins = distribution.get("1", 0)
    assert cf["outcome"]["winFraction"] == pytest.approx(n_wins / cf["nSeeds"], abs=1e-3)
    assert sum(distribution.values()) == cf["nSeeds"]
