"""Drift guard for the frontend fixture.

The frontend currently renders from `frontend/src/fixtures/race.json`,
generated by `scripts/export_fixture.py`, because Phase 5's API isn't built.
A hand-exported fixture goes stale silently the moment anything upstream is
refit — and this session's parameters moved three times. The concrete cost:
a 25% win fraction measured at `MIN_FOLLOWING_GAP_S = 0.3` was quoted in
prose after the floor had already been refitted to 0.580, i.e. the number
was wrong when it was written down.

So the fixture carries a parameter fingerprint, and this test asserts it
matches the live constants. If a refit invalidates the fixture, a test fails
instead of the UI quietly showing a number nobody re-derived. Same pattern as
`scripts/fit_noise_autocorrelation.py` and `scripts/fit_min_following_gap.py`
failing loudly on drift.

Fix on failure: re-run `python backend/scripts/export_fixture.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from pitwall.simulation.lap_time import AR1_PHI
from pitwall.simulation.position import MIN_FOLLOWING_GAP_S

FIXTURES_DIR = Path(__file__).resolve().parents[2] / "frontend" / "src" / "fixtures"
FIXTURE_PATH = FIXTURES_DIR / "race.json"
RACES_DIR = FIXTURES_DIR / "races"


@pytest.fixture(scope="module")
def fixture() -> dict:
    if not FIXTURE_PATH.exists():
        pytest.skip(f"{FIXTURE_PATH} not generated; run scripts/export_fixture.py")
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def _race_files() -> list[Path]:
    """Every generated file: per-race base files and per-driver candidate files."""
    return sorted(RACES_DIR.glob("*.json")) if RACES_DIR.exists() else []


def _driver_files() -> list[Path]:
    """Per-driver candidate files only, excluding the shared per-race base."""
    return [p for p in _race_files() if not p.name.endswith("__base.json")]


def _base_files() -> list[Path]:
    return [p for p in _race_files() if p.name.endswith("__base.json")]


@pytest.fixture(scope="module")
def live_fingerprints() -> dict[str, dict]:
    """One fresh fit per race, reused across every driver file for that race.

    Phase 6.2 produces 98 per-driver files. Fitting once per file would refit
    each race twenty times over.
    """
    from pitwall.ingestion.catalogue import get_entry
    from pitwall.ingestion.loader import load_race
    from pitwall.parameters.fit_all import (
        fit_catalogue_with_pooled_dirty_air,
        driver_params_digest,
    )

    race_keys = sorted({path.name.split("__")[0] for path in _race_files()})
    result: dict[str, dict] = {}
    for race_key in race_keys:
        entry = get_entry(race_key)
        snapshot, _ = load_race(entry.year, entry.fastf1_event_identifier)
        params = fit_catalogue_with_pooled_dirty_air([snapshot])[race_key]
        result[race_key] = {
            "minFollowingGapS": MIN_FOLLOWING_GAP_S,
            "ar1Phi": AR1_PHI,
            "pitLaneLossS": round(params.pit_lane_loss_s, 4),
            "overtakeDifficulty": round(params.overtake_difficulty, 6),
            "dirtyAirMaxPenaltyS": round(params.dirty_air.max_penalty_s, 6),
            "dirtyAirDecayScaleS": round(params.dirty_air.decay_scale_s, 6),
            "driverParamsDigest": driver_params_digest(params),
        }
    return result


# ---------------------------------------------------------------------------
# Phase 6.2: the per-driver expansion. The fingerprint guard now covers EVERY
# generated file, not one — 98 files is 98 chances for a stale number to reach
# the UI, and the whole point of the fingerprint is that staleness fails a test
# instead of shipping.
# ---------------------------------------------------------------------------


def test_every_race_file_fingerprint_matches_live_code(live_fingerprints):
    files = _race_files()
    if not files:
        pytest.skip("no per-driver fixtures; run scripts/build_fixtures.py")

    stale: list[str] = []
    for path in files:
        payload = json.loads(path.read_text(encoding="utf-8"))
        expected = live_fingerprints[payload["meta"]["raceKey"]]
        if payload["meta"]["paramFingerprint"] != expected:
            stale.append(path.name)
    assert not stale, (
        f"{len(stale)} fixture file(s) were generated under different parameters and are "
        f"stale: {stale[:5]}{'...' if len(stale) > 5 else ''}. "
        "Re-run scripts/build_fixtures.py."
    )


def test_every_driver_file_has_the_required_shape():
    files = _driver_files()
    if not files:
        pytest.skip("no per-driver fixtures; run scripts/build_fixtures.py")

    for path in files:
        payload = json.loads(path.read_text(encoding="utf-8"))
        meta, candidates = payload["meta"], payload["candidates"]
        assert meta["driver"] and meta["raceKey"], path.name
        # One file per (driver, STOP): the UI shows one stop at a time, so a
        # two-stop driver was downloading twice what was displayed.
        assert path.name == f"{meta['raceKey']}__{meta['driver']}__s{meta['stopLap']}.json"
        assert {c["originalLap"] for c in candidates} == {meta["stopLap"]}, (
            f"{path.name}: candidates for a stop this file does not name"
        )
        assert meta["realPitLaps"], f"{path.name}: eligible drivers must have a real stop"
        assert candidates, f"{path.name}: no candidates generated"

        # Now that a file is exactly one stop, at most one candidate in it can
        # reproduce reality. Still not "exactly one": a final stop with no
        # following stint cannot be shifted and the engine correctly refuses —
        # 2019 Australian RIC pitted on lap 1 for a new front wing and then
        # retired with damage on lap 29, so that second in-lap IS the retirement.
        real_marked = [c for c in candidates if c["isReal"]]
        assert len(real_marked) <= 1, f"{path.name}: {len(real_marked)} reality-reproducing candidates"
        for candidate in candidates:
            assert candidate["deltaVsSimulatedReal"], f"{path.name}: candidate has no delta trace"
            assert candidate["classification"], f"{path.name}: candidate has no distribution"


def test_no_driver_file_stores_per_seed_lap_state():
    """The storage rule that makes the payload loadable at all: summaries only.

    485,100 simulations back these files. Serialising per-seed `LapState`
    arrays would be gigabytes, and an earlier draft that stored 12 individual
    seed traces per candidate was already 71% seed data and 2-3x the size
    budget.

    Three traces per candidate *are* stored, deliberately -- a p10-p90 band
    cannot show a bimodal ensemble, so the median can sit where no seed ever
    was. This test therefore pins the shape that keeps them affordable: a hard
    cap on the count, and values aligned to the delta series rather than each
    trace repeating the lap column.
    """
    files = _race_files()
    if not files:
        pytest.skip("no per-driver fixtures; run scripts/build_fixtures.py")

    banned = {"lapStates", "seedSeries", "states"}
    for path in _driver_files():
        payload = json.loads(path.read_text(encoding="utf-8"))
        for candidate in payload["candidates"]:
            present = banned & set(candidate)
            assert not present, f"{path.name}: per-seed state stored ({present})"

            traces = candidate["seedTraces"]
            assert len(traces) <= 3, f"{path.name}: {len(traces)} seed traces stored"
            n_laps = len(candidate["deltaVsSimulatedReal"])
            for trace in traces:
                assert set(trace) == {"seed", "values"}, f"{path.name}: seed trace carries extra keys"
                assert len(trace["values"]) == n_laps, (
                    f"{path.name}: seed trace has {len(trace['values'])} values against "
                    f"{n_laps} laps -- the alignment the frontend relies on is broken"
                )
            # Same for the replay-error diagnostic.
            assert len(candidate["deltaVsActual"]) == n_laps, f"{path.name}: deltaVsActual misaligned"
            assert len(candidate["positions"]) == n_laps, f"{path.name}: positions misaligned"


def test_race_file_sizes_stay_within_the_stated_budget():
    """The spec's sizing rule, enforced rather than measured once.

    "Per-driver files should land in the low hundreds of kilobytes... if they
    come out much larger, the stored-fields list is wrong." A regression here
    should fail loudly, because the failure mode is a UI that stops loading.
    """
    files = _race_files()
    if not files:
        pytest.skip("no per-driver fixtures; run scripts/build_fixtures.py")

    # Raised from 600KB when the candidates gained a second delta series, three
    # seed trajectories and per-compound fit provenance. The number that matters
    # is the median (~300KB); this is a regression ceiling, not a target, and it
    # exists so a stored-fields mistake fails loudly instead of shipping a UI
    # that stops loading.
    oversized = [(p.name, p.stat().st_size // 1024) for p in files if p.stat().st_size > 650 * 1024]
    assert not oversized, f"files above the 600KB ceiling: {oversized}"


def test_monaco_is_present_and_labelled_rather_than_omitted():
    """A visible caveat is more useful than a missing option."""
    files = _race_files()
    if not files:
        pytest.skip("no per-driver fixtures; run scripts/build_fixtures.py")

    monaco = [p for p in files if p.name.startswith("2019_monaco__")]
    assert monaco, "Monaco must be generated, not skipped for being excluded from the gate"
    for path in monaco:
        note = json.loads(path.read_text(encoding="utf-8"))["meta"]["excludedFromGate"]
        assert note and "gate" in note.lower(), f"{path.name}: missing the exclusion caveat"

    other = next(p for p in files if not p.name.startswith("2019_monaco__"))
    assert json.loads(other.read_text(encoding="utf-8"))["meta"]["excludedFromGate"] is None


def test_fixture_simulation_constants_match_live_code(fixture):
    fingerprint = fixture["meta"]["paramFingerprint"]
    assert fingerprint["minFollowingGapS"] == pytest.approx(MIN_FOLLOWING_GAP_S), (
        "fixture was generated with a different MIN_FOLLOWING_GAP_S -- the margin the UI "
        "reports is stale. Re-run scripts/export_fixture.py."
    )
    assert fingerprint["ar1Phi"] == pytest.approx(AR1_PHI), (
        "fixture was generated with a different AR1_PHI -- the ensemble spread (and so the "
        "win fraction) is stale. Re-run scripts/export_fixture.py."
    )


def test_fixture_fitted_parameters_match_a_fresh_fit(fixture):
    """The fingerprint also covers *fitted* values, which move when the
    fitting code changes even if no constant does."""
    from pitwall.ingestion.catalogue import get_entry
    from pitwall.ingestion.loader import load_race
    from pitwall.parameters.fit_all import fit_catalogue_with_pooled_dirty_air

    entry = get_entry(fixture["meta"]["raceKey"])
    snapshot, _ = load_race(entry.year, entry.fastf1_event_identifier)
    params = fit_catalogue_with_pooled_dirty_air([snapshot])[snapshot.race_key]

    fingerprint = fixture["meta"]["paramFingerprint"]
    assert fingerprint["pitLaneLossS"] == pytest.approx(params.pit_lane_loss_s, abs=1e-3)
    assert fingerprint["overtakeDifficulty"] == pytest.approx(params.overtake_difficulty, abs=1e-5)
    assert fingerprint["dirtyAirMaxPenaltyS"] == pytest.approx(params.dirty_air.max_penalty_s, abs=1e-5)
    assert fingerprint["dirtyAirDecayScaleS"] == pytest.approx(params.dirty_air.decay_scale_s, abs=1e-5)


def test_fixture_carries_seed_traces_not_only_a_median(fixture):
    """Spec 6.10: a counterfactual is a distribution. The chart must be able
    to draw real seed traces rather than presenting a median line as if it
    were a single universe any seed produced."""
    cf = fixture["counterfactual"]
    assert cf["seedSeries"], "no per-seed traces exported; the chart can only draw a median"
    assert len(cf["seedSeries"]) >= 5
    for trace in cf["seedSeries"]:
        assert trace["points"], f"seed {trace['seed']} has no post-fork points"
        assert min(p["lap"] for p in trace["points"]) >= cf["divergenceLap"]


def test_fixture_win_fraction_is_consistent_with_its_own_distribution(fixture):
    """Guards the specific error that motivated this file: a win fraction
    quoted from a different parameter set than the distribution beside it."""
    cf = fixture["counterfactual"]
    distribution = cf["outcome"]["positionDistribution"]
    n_wins = distribution.get("1", 0)
    assert cf["outcome"]["winFraction"] == pytest.approx(n_wins / cf["nSeeds"], abs=1e-3)
    assert sum(distribution.values()) == cf["nSeeds"]


def test_fixture_stints_carry_real_tyre_ages_not_stint_length(fixture):
    """Tyre age and stint length are different quantities: a stint can start
    on used tyres, so `end_lap - start_lap + 1` understates the age the tyre
    model was actually asked about. The frontend displayed ages derived that
    way and they were simply wrong (VER's 2019 Hungary opening stint runs
    laps 1-25 at ages 4-28, so it read 25 instead of 28).

    Pinned because it's a named property now. Note the age *span* always
    equals the lap span (age advances one per lap) — that's not the tell. The
    tell is the absolute age: `endTyreAge` must differ from stint *length*
    (`endLap - startLap + 1`) for any stint that began on used tyres, which
    is exactly what the buggy derivation produced.
    """
    stints = fixture["stints"]
    assert stints
    for stint in stints:
        assert "startTyreAge" in stint and "endTyreAge" in stint
        # Internal consistency: age advances exactly one per lap within a stint.
        assert stint["endTyreAge"] - stint["startTyreAge"] == stint["endLap"] - stint["startLap"]

    started_used = [s for s in stints if s["startTyreAge"] > 1]
    assert started_used, "expected at least one stint starting on used tyres in this catalogue"

    # The specific bug: deriving age from length. At least one stint must
    # disagree with that derivation, or the guard proves nothing.
    disagrees_with_length = [
        s for s in stints if s["endTyreAge"] != (s["endLap"] - s["startLap"] + 1)
    ]
    assert disagrees_with_length, (
        "no stint's real end-age differs from its lap count, so this guard couldn't "
        "detect age being re-derived from stint length"
    )


def test_real_pit_lap_is_the_minimum_extrapolation(fixture):
    """The DecisionPanel's teaching claim, pinned as a data property.

    Reality is the zero-extrapolation point *by construction*: observed tyre
    ages are definitionally what happened, so every counterfactual leaves the
    evidence somewhere. Shifting a stop lengthens one stint and shortens
    another, which means there is no "safe direction" -- an earlier stop
    over-extends the following stint, a later one over-extends the current.

    This was asserted the other way round at one point (earlier = safe) and
    the candidate table falsified it, so it is a test now rather than a
    comment.
    """
    candidates = fixture["counterfactual"]["candidates"]
    assert candidates

    real = [c for c in candidates if c["isReal"]]
    assert len(real) == 1, "expected exactly one candidate marked as the real pit lap"
    assert real[0]["beyondEvidenceLaps"] == 0, (
        "the real pit lap must require zero extrapolation -- observed tyre ages come "
        "from precisely that strategy"
    )

    minimum = min(c["beyondEvidenceLaps"] for c in candidates)
    assert real[0]["beyondEvidenceLaps"] == minimum

    # Both directions must climb: this is the V, and it's what makes "no safe
    # direction" true rather than rhetorical.
    real_lap = real[0]["newLap"]
    earlier = [c for c in candidates if c["newLap"] < real_lap]
    later = [c for c in candidates if c["newLap"] > real_lap]
    if earlier:
        assert max(c["beyondEvidenceLaps"] for c in earlier) > 0, "pitting earlier should extrapolate"
    if later:
        assert max(c["beyondEvidenceLaps"] for c in later) > 0, "pitting later should extrapolate"


def test_extrapolation_grows_monotonically_away_from_the_real_lap(fixture):
    """Within each arm the exposure should grow steadily, not jump around --
    that monotonicity is what makes dragging the slider legible as a gradient
    rather than noise."""
    candidates = {c["newLap"]: c for c in fixture["counterfactual"]["candidates"]}
    real_lap = next(c["newLap"] for c in candidates.values() if c["isReal"])

    earlier = [candidates[lap] for lap in sorted(candidates) if lap < real_lap]
    for nearer, further in zip(earlier[1:], earlier, strict=False):
        # Walking back toward the real lap, exposure must not increase.
        assert nearer["beyondEvidenceLaps"] <= further["beyondEvidenceLaps"]


def test_every_race_has_a_base_file_carrying_the_shared_field_data():
    """Field mode needs every driver's real gap-to-leader, and the per-driver
    candidate files deliberately don't duplicate it — 20 copies of the same
    field-wide series per race would be waste. So each race ships one base
    file. Selecting a race fetches that once; selecting a driver then fetches
    exactly one candidate file.

    This omission was caught by building the production bundle and finding the
    field-mode data had nowhere to come from.
    """
    bases = _base_files()
    if not bases:
        pytest.skip("no fixtures; run scripts/build_fixtures.py")

    driver_races = {p.name.split("__")[0] for p in _driver_files()}
    base_races = {p.name.split("__")[0] for p in bases}
    assert driver_races == base_races, "every race with driver files needs a base file"

    for path in bases:
        payload = json.loads(path.read_text(encoding="utf-8"))
        assert payload["realSeries"], f"{path.name}: no real gap-to-leader series"
        assert payload["drivers"], f"{path.name}: no driver list"
        assert payload["stints"], f"{path.name}: no stints"
        # The flag the UI needs to know which drivers are selectable.
        assert any(d["hasCandidates"] for d in payload["drivers"]), path.name
        # Base files are shared, so they must stay small.
        assert path.stat().st_size < 120 * 1024, f"{path.name} is {path.stat().st_size // 1024}KB"


def test_a_moved_pit_stop_produces_a_non_degenerate_delta():
    """The regression guard for the bug that survived every other test here.

    The delta was originally stored as the difference of two *gap-to-leader*
    series. Gap-to-leader is floored at zero for whoever is leading, so for a
    driver who leads in both timelines the difference is identically 0.000 —
    and on the demo case (VER led laps 1-66 of Hungary 2019) it was exactly
    that on 26 of the 31 simulated laps, p10 and p90 included. Every
    fingerprint, shape, size and monotonicity assertion passed while the chart
    reported "no difference at all" for moving a pit stop by 27 laps. Only
    opening it in a browser found it.

    So: for a candidate that moves a stop by a wide margin, the post-fork delta
    must actually vary. Cumulative race time has no floor, which is why it is
    now the stored variable.
    """
    driver_files = _driver_files()
    if not driver_files:
        pytest.skip("no fixtures; run scripts/build_fixtures.py")

    checked = 0
    for path in driver_files:
        payload = json.loads(path.read_text(encoding="utf-8"))
        for candidate in payload["candidates"]:
            shift = abs(candidate["newLap"] - candidate["originalLap"])
            # Post-fork laps only; the anchor row is zero by construction.
            post_fork = [
                row for row in candidate["deltaVsSimulatedReal"] if row[0] >= candidate["divergenceLap"]
            ]
            if shift < 10 or len(post_fork) < 10:
                continue
            checked += 1
            zero_laps = sum(1 for row in post_fork if row[1] == 0.0 and row[2] == 0.0 and row[3] == 0.0)
            assert zero_laps < len(post_fork) / 2, (
                f"{path.name} lap {candidate['originalLap']}->{candidate['newLap']}: "
                f"{zero_laps} of {len(post_fork)} post-fork laps have an identically "
                "zero delta and band. The stored variable is degenerate."
            )
            # A stop moved 10+ laps must produce a visible *excursion*. The
            # first version of this asserted on the final delta instead and was
            # wrong: 2019 Australian GRO 15->25 finishes 0.26s apart, because
            # both timelines have paid the same pit loss before he retires on
            # lap 29, leaving only the tyre-pace integral. The endpoints can
            # legitimately reconverge; the excursion between them cannot vanish.
            medians = [row[1] for row in post_fork]
            assert max(medians) - min(medians) > 1.0, (
                f"{path.name} lap {candidate['originalLap']}->{candidate['newLap']}: "
                f"post-fork delta spans only {max(medians) - min(medians):.3f}s, "
                f"which a {shift}-lap change cannot plausibly produce"
            )

    assert checked > 100, f"only {checked} wide-shift candidates checked; guard is too weak"


def test_the_reality_reproducing_candidate_has_exactly_zero_decision_effect():
    """The invariant that pins the baseline.

    `deltaVsSimulatedReal` measures the alternate against an override-free fork
    at the same lap with the same seed. Phase 4's no-op test already pins that
    reference byte-for-byte against a no-op `ChangePitLap`, so for the candidate
    that reproduces reality the decision effect must be exactly 0.000 -- not
    approximately zero. Any drift here means the baseline has stopped being the
    paired reference and every candidate's delta has become uninterpretable.

    `deltaVsActual` on the same candidate is the simulator's replay error, and it
    is emphatically NOT zero (-7.4s by lap 70 on Hungary/VER). That contrast is
    the reason both series exist: differencing against actual times would put
    that 7.4s into every candidate, swamping any effect of a couple of seconds.
    """
    driver_files = _driver_files()
    if not driver_files:
        pytest.skip("no fixtures; run scripts/build_fixtures.py")

    checked = 0
    for path in driver_files:
        payload = json.loads(path.read_text(encoding="utf-8"))
        for candidate in payload["candidates"]:
            if not candidate["isReal"]:
                continue
            checked += 1
            for lap, median, low, high in candidate["deltaVsSimulatedReal"]:
                assert (median, low, high) == (0.0, 0.0, 0.0), (
                    f"{path.name} lap {lap}: reality-reproducing candidate has a "
                    f"non-zero decision effect {median}s -- the paired baseline is broken"
                )
            for trace in candidate["seedTraces"]:
                assert set(trace["values"]) == {0.0}, f"{path.name}: seed trace is non-zero"

    assert checked > 50, f"only {checked} reality-reproducing candidates found"


def test_every_implausible_answer_has_a_named_cause():
    """An answer past the plausibility bound must be attributable.

    The bound is a symptom test -- twice the fitted pit-lane loss -- and on its
    own it only says "this number is too big". Auditing what it caught turned up
    two unrelated causes it cannot distinguish:

      - 2019 Hungary VER 67->40, -52.8s, entirely pace, resting on a SOFT cell
        fitted from 2 observations with a degradation rate of exactly 0.0 s/lap
        and r2 = nan, relied on for 30 post-fork laps.
      - 2019 Hungary BOT 5->20, -108.4s, of which -86.5s is accumulated held-up
        time and only -21.9s pace, on cells that are perfectly well fitted.

    So every implausible candidate must be explained by at least one of: running
    past observed tyre age, resting on a degenerate fit, or being dominated by
    traffic rather than pace. One that is implausible with none of those is an
    unexplained engine result, and this test is where it should surface rather
    than in the UI as a confident minute of gain.
    """
    driver_files = _driver_files()
    if not driver_files:
        pytest.skip("no fixtures; run scripts/build_fixtures.py")

    unexplained, implausible, total = [], 0, 0
    for path in driver_files:
        payload = json.loads(path.read_text(encoding="utf-8"))
        for candidate in payload["candidates"]:
            total += 1
            verdict = candidate["plausibility"]
            # Every candidate carries the verdict, plausible or not.
            assert set(verdict) >= {
                "finalDeltaS",
                "implausible",
                "trafficS",
                "paceS",
                "restsOnDegenerateFit",
                "cause",
            }, f"{path.name}: incomplete plausibility verdict"
            assert "fitReliance" in candidate, f"{path.name}: no fit reliance"

            if not verdict["implausible"]:
                assert verdict["cause"] is None, f"{path.name}: plausible candidate has a cause"
                continue
            implausible += 1
            assert verdict["cause"] in {
                "degenerateFit",
                "traffic",
                "extrapolation",
                "unexplained",
            }, f"{path.name}: unknown cause {verdict['cause']!r}"
            if verdict["cause"] == "unexplained":
                unexplained.append(
                    f"{path.name} {candidate['originalLap']}->{candidate['newLap']}: "
                    f"{verdict['finalDeltaS']}s ({verdict['sPerLap']}s/lap)"
                )

    assert implausible > 0, "no implausible candidates at all -- is the bound wired up?"

    # Unexplained is a permitted verdict, not a passing grade, and it currently
    # never fires: the taxonomy accounts for all 2,419 implausible candidates
    # (extrapolation 1,971, traffic 314, degenerate fit 134).
    #
    # It did fire before the degradation fallback chain was fixed -- 2021 Spanish
    # HAM 28->12 and PER 57->44, both ~+58s with well-fitted cells and inside
    # observed tyre age. Correcting the chain changed the fitted pit-lane loss
    # (it is measured against expected clean pace, which depends on the tyre
    # models), which moved the bound, and both fell inside it. So the residual
    # was downstream of a real parameter bug rather than a genuine third cause.
    # The guard stays because the next one might not be.
    share = len(unexplained) / max(1, total)
    # Tightened from 0.005 to just above the observed 0.00025 (2 of 8,085). A cap
    # with 20x headroom is not a regression guard, it is a rubber stamp — the same
    # shape of mistake as the fallback-fraction ceiling that sat at 40% while the
    # race that mattered was at 19%.
    assert share < 0.001, (
        f"{len(unexplained)} of {total} candidates ({share:.2%}) are implausible with no "
        "identified cause, which is too many to wave through: " + "; ".join(unexplained[:10])
    )


def test_every_driver_file_carries_its_per_driver_constants_once():
    """The per-driver constants live in `meta`, not on all ~140 candidates.

    `tyreCells` (observation count, r2, slope, cliff per compound) and the
    plausibility bound are identical across every candidate a driver has.
    Repeating them measured 7.5% of the payload for no information. Each candidate
    keeps only `fitReliance` — how many post-fork laps *that* candidate runs on
    each compound — which is the part that actually varies.

    Asserted because the join is now the frontend's job, and a candidate naming a
    compound absent from `meta.tyreCells` would silently lose its caveat.
    """
    files = _driver_files()
    if not files:
        pytest.skip("no per-driver fixtures; run scripts/build_fixtures.py")

    for path in files:
        payload = json.loads(path.read_text(encoding="utf-8"))
        meta = payload["meta"]
        assert meta["tyreCells"], f"{path.name}: no tyre cells in meta"
        assert meta["plausibilityBoundS"] > 0, f"{path.name}: no plausibility bound"
        known = {cell["compound"] for cell in meta["tyreCells"]}
        for candidate in payload["candidates"]:
            assert "tyreCells" not in candidate, f"{path.name}: cells still repeated per candidate"
            assert "boundS" not in candidate["plausibility"], f"{path.name}: bound still repeated"
            unknown = set(candidate["fitReliance"]) - known
            assert not unknown, f"{path.name}: reliance on compounds missing from meta: {unknown}"


def test_stored_per_lap_positions_are_present_and_ordered():
    """Phase 6.4 reads the order at a lap; it never interpolates one.

    That only works if position is stored per lap on both sides. The spec claimed
    6.4 "needs no new data" because per-lap positions exist for every seed — true
    of the engine's `LapState`, but the precompute never stored them, so they had
    to be added. This asserts both halves are there and are sane.
    """
    driver_files, base_files = _driver_files(), _base_files()
    if not driver_files:
        pytest.skip("no per-driver fixtures; run scripts/build_fixtures.py")

    for path in base_files:
        payload = json.loads(path.read_text(encoding="utf-8"))
        positions = payload["realPositions"]
        assert len(positions) >= 15, f"{path.name}: only {len(positions)} drivers have positions"
        for code, series in positions.items():
            laps = [lap for lap, _ in series]
            assert laps == sorted(laps), f"{path.name} {code}: laps out of order"
            for _, position in series:
                assert 1 <= position <= 26, f"{path.name} {code}: position {position}"

    for path in driver_files:
        payload = json.loads(path.read_text(encoding="utf-8"))
        for candidate in payload["candidates"]:
            for entry in candidate["positions"]:
                if entry is None:
                    continue
                median, best, worst = entry
                assert 1 <= best <= median <= worst <= 26, (
                    f"{path.name}: position spread {entry} is not ordered best<=median<=worst"
                )
